### PR TITLE
Optimize memory usage in `homogeneous_DUO_update` via in-place update

### PR DESCRIPTION
**Pull request by EwoutH**
This commit resolves a memory consumption issue in the `homogeneous_DUO_update` method by replacing the previous array reallocation with an in-place update using `np.place`. The old implementation created new NumPy arrays in each update cycle, leading to unnecessary memory overhead.

With the in-place update, total memory usage was reduced from 1189 MB to 471 MB.

### Changes
- Switched to `np.place` for in-place updates of `s.route_pref`.
- Removed unnecessary temporary array creation to reduce memory footprint.

Part of https://github.com/toruseo/UXsim/issues/143.

### CODE REVIEW

**Comment by EwoutH** [comment]
@toruseo The failure values look very small, could it be that just some rounding error and the tolerances are a bit tight?

**Comment by toruseo** [comment]
The diff is not small. I guess (I dont fully understand the vectorizatoin technique used here) the modification broke the route choice logic.

**Comment by EwoutH** [comment]
Yes, took a look again, you’re right.

I will try a few other approaches, and also investigate `dist_record`.

**Comment by toruseo** [comment]
Closing, as better one is implemented by https://github.com/toruseo/UXsim/pull/146

**Pull request closed without merging**
