### PR TITLE
Add pre-commit configuration, upgrade to Python 3.9+ syntax, remove trailing whitespaces

### PR DESCRIPTION
**Pull request by EwoutH**
This commit adds a [pre-commit](https://pre-commit.com/) configuration, which allows running a few tools automatically both locally and in CI.

Currently:
 - It adds [pyupgrade](https://github.com/asottile/pyupgrade)
 - It check for trailing whitespaces and if toml and yaml syntax is correct
 - Updates itself monthly (using [pre-commit.ci](https://pre-commit.ci/))

For automatically running pre-commit in CI, I would recommend enabling it on https://pre-commit.ci/.

### CODE REVIEW

**Comment by EwoutH** [comment]
Thanks for merging!

Feel free to use _Squash and merge_ merge method for PRs with a single commit, or in this case, the _Rebase and merge_ method for PRs with multiple commits. That results in a cleaner commit history. See the [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request) for more details.

image

**Comment by EwoutH** [comment]
> For automatically running pre-commit in CI, I would recommend enabling it on https://pre-commit.ci/.

Please don’t forget to consider this :)

**Comment by EwoutH** [comment]
@toruseo have you thought about enabling pre-commit.ci?

**Comment by toruseo** [comment]
I will look at it. Please give me some time as it may change my workflow a lot.

**Comment by EwoutH** [comment]
Thanks! What do you think would change? With my experience with pre-commit, it’s typically enable-and-forget. It’s made to make your life easier :)

**Comment by toruseo** [comment]
Sorry for the delay in addressing this matter. I haven't had the time to learn how to use pre-commit (at least I understand that while it makes code management easier, it does not change the simulation functionality). Given that situation, keeping a pre-commit file in the repo could be confusing, so I've decided to remove it for the time being. I have added the file to `.gitignore`, so I hope it will not change your workflow.

I really appreciate your contributions and suggestions. Please feel free to propose new ideas!

**Pull request merged**
