### PR TITLE
UXsim: Add new get_all_distances method to RouteChoice

### PR DESCRIPTION
**Pull request by EwoutH**
`get_all_distances` is a new helper method that returns distance array in the same format as `s.dist`. This way you can look up distances the same way as you look up travel time.

Usage:
```Python
distance_array = w.ROUTECHOICE.get_all_distances()

some_distance = distance_array[o_node.id][d_node.id]
some_travel_time = uw.ROUTECHOICE.dist[o_node.id][d_node.id]
```
One consideration could be saving this matrix internally in the `RouteChoice` class, instead of returning it.

This PR was validated that it outputs the same distances as NetworkX.

### CODE REVIEW

**Comment by toruseo** [comment]
what is this for?

**Comment by toruseo** [comment]
ok, so this is not for simulation itself, but for users' convenience.

Then it is better to add a similar method to `World` class itself, not here. I will do that very soon

Idea behind it: `RouteChoice` class and `node.id` are basically encapsulated (or hidden) for basic users. Advanced users may access them to do advanced things, but they are recommended to define their own helper functions outside (downstream?) of uxsim, because they may not be very general. But distance info is general and useful as you pointed out, so it worth adding

**Comment by toruseo** [comment]
Closing this PR as almost equivalent function `World.get_shortest_path_distance_between_all_nodes(return_matrix=True)` is implemented and tested by https://github.com/toruseo/UXsim/pull/136
For an example, see the added test.

One difference is that the return value in this PR is a tuple of 1d arrays as specified by 
```
distances = *dijkstra(csr_matrix(distances), directed=directed, return_predecessors=False),
return distances
```
, which seems not common, so `World.get_shortest_path_distance_between_all_nodes(return_matrix=True)` returns simple 2d array instead.

**Comment by EwoutH** [comment]
Thanks!

**Pull request closed without merging**
