### PR TITLE
Speed up `homogeneous_DUO_update`

### PR DESCRIPTION
**Pull request by toruseo**

### CODE REVIEW

**Comment by EwoutH** [comment]
Really awesome! I will run a quick test tomorrow on my model.

One small suggestion: It would be nice to keep PRs somewhat atomic, meaning they each contain one distinct feature or change. That makes following and potentially reviewing changes much easier, as well as tracking down accidental bugs.

**Comment by EwoutH** [comment]
This is really impressive! I will be simulating the Rotterdam region, with hundreds of thousands vehicles, and now I might be able to run locally instead of needing to reserve our supercomputer for extensive time.

It's always nice when open-source proves again life isn't a zero-sum game!

**Comment by EwoutH** [comment]
Could you tag a new version with this speedup?

**Comment by toruseo** [comment]
released as v1.4.0

**Pull request merged**
